### ISSUE TITLE
Cannot make a post with the same topic tag as an already existing post.

### ISSUE THREAD

**Issue by ModoUnreal** [ModoUnreal/nuncio#1]
So I want to make a post with the tag 'meta' however when I do I get the following traceback:

    Traceback (most recent call last)
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    Open an interactive python shell in this frameresponse = self.handle_exception(e)
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
    File "d:\files\flask\dew\env\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "d:\files\flask\dew\env\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
    File "d:\files\flask\dew\env\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "d:\files\flask\dew\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
    File "D:\files\flask\dew\nuncio\app\routes.py", line 33, in submit
    db.session.commit()
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\session.py", line 943, in commit
    self.transaction.commit()
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\session.py", line 467, in commit
    self._prepare_impl()
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\session.py", line 447, in _prepare_impl
    self.session.flush()
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
    self._flush(objects)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\session.py", line 2344, in _flush
    flush_context.execute()
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
    rec.execute(self)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 556, in execute
    uow
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\orm\persistence.py", line 866, in                             
    _emit_insert_statements
    execute(statement, params)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in             _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in     _execute_clauseelement
    compiled_sql, distilled_params
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in     _execute_context
    context)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in     _handle_dbapi_exception
    exc_info
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in     _execute_context
    context)
    File "d:\files\flask\dew\env\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
    sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: topic.tag_name [SQL:         'INSERT INTO topic (tag_name) VALUES (?)'] [parameters: ('Meta',)] (Background on this error at:     http://sqlalche.me/e/gkpj)

**Comment by ModoUnreal** [comment]
Working on this now......

**Comment by ModoUnreal** [comment]
Fixed lemme just push it
