### ISSUE TITLE
Error occurs when Register a new user

### ISSUE THREAD

**Issue by ns23** [ModoUnreal/nuncio#12]
After doing the setup tried to register a new user. got below error

(env) ➜  nuncio git:(master) ✗ python nuncio.py
Serving on http://localhost:5000[2018-05-20 15:13:29,799] ERROR in app: Exception on /auth/register [POST]
Traceback (most recent call last):  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context    context)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ns23/Documents/code/python/nuncio/app/auth/routes.py", line 45, in register
    if form.validate_on_submit():
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/ns23/Documents/code/python/nuncio/app/auth/forms.py", line 45, in validate_username
    user = User.query.filter_by(username=username.data).first()
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2789, in first
    ret = list(self[0:1])
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2581, in __getitem__
    return list(res)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ns23/Documents/code/python/nuncio/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: 'SELECT user.id AS user_id, user.usernameAS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.scores AS user_scores, user.importance_debt AS user_importance_debt \nFROM user \nWHERE user.username = ?\n LIMIT ? OFFSET ?'] [parameters: ('ns23', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by ModoUnreal** [comment]
Have you tried running flask db init before trying to run the server? If that doesn't work try doing `flask db migrate -m "users table"`.

**Comment by ns23** [comment]
I tried  Got same error

**Comment by ModoUnreal** [comment]
I forgot to mention in the README that the user has to then do `flask db upgrade`, apologies.

**Comment by ModoUnreal** [comment]
I'm going to close this now, please notify me if this issue is still ongoing with your copy.

**Comment by ns23** [comment]
Okay.. I'm glad that I could help
